
server.port: 8080
server.ssl.enabled: false

## sizzang
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sizzang.cggdc2hymcot.ap-northeast-2.rds.amazonaws.com/sizzang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: sizzang
#    password: sizzangssafy

  #sizzang
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sizzang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  profiles:
    active: secret

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        
jwt:
  secretKey: "77669629e79bec9fdc11391e28bb7232c80660499499add816f4ae3ff1a5c10a1aa4fffadddd0b725957934271e1c54a061e2f2956ebba3727aa7aa7a3fee8c6480a97"
  access:
    expiration: 1800000 
    header: Authorization
  refresh:
    expiration: 1209600000 
    header: Authorization-refresh

